### ISSUE TITLE
Template not detected from shared library

### ISSUE THREAD

**Issue by equinusocio** [gavinmcfarland/figma-table-creator#2]
Hi Gavin, we are trying to use this plugin within my team in order to create tables using components from the DS, but my teammates have issues while running the plugin the first time.

Here what I did:

1. I created and published a shared component library with the table template inside. (I'm the only person who can edit it, others are in read only mode)
2. I shared and linked the library in every current and new files.

Now, when my teammates run the plugin inside the file, it asks to create a new local table template, without asking for existing ones, even if the library with the shared template is linked.

The strange thing is that if i run the plugin in the same file, the plugin show me the "existing template" button, and i can pick the one from the shared library. Starting from here, my teammates can run the plugin and use the shared template (the plugin is not asking to create a new template anymore). So i have to run the plugin once for every file in order to enable them to use the shared table template.

This is what i see when i run the plugin inside their files.

![CleanShot 2022-08-02 at 15 18 49](https://user-images.githubusercontent.com/10454741/182384372-eb5991fe-13e9-4ffb-aee8-dbd59cb50b6f.png)

When they run the plugin the "Existing template" button is missing so they are forced to create a new local template.

**Comment by gavinmcfarland** [comment]
Just remembering to close this issue. As a short term fix team members can now import templates by clicking "Import Template" and dragging them from the assets panel. Thanks again for your help on this one.
